name: Build and Test Desktop App

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-desktop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Create firebase.properties file
        env:
          FIREBASE_PROPERTIES_CONTENT: ${{ secrets.FIREBASE_PROPERTIES_CONTENT }}
        run: |
          echo "$FIREBASE_PROPERTIES_CONTENT" > ./shared/src/jvmMain/resources/firebase.properties

      - name: Assemble Desktop App
        run: ./gradlew :composeApp:assemble --warning-mode fail

      - name: Run Desktop Tests
        env:
          WELK_TEST_USERNAME: ${{ secrets.WELK_TEST_USERNAME }}
          WELK_TEST_PASSWORD: ${{ secrets.WELK_TEST_PASSWORD }}
        run: ./gradlew :composeApp:desktopTest

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: desktop-test-results
          path: composeApp/build/reports/tests/desktopTest/
          retention-days: 7
