name: Build and Test Desktop App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-desktop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Create firebase.properties file
        run: |
          echo "firebase.apiKey=dummy" > ./shared/src/jvmMain/resources/firebase.properties
          echo "firebase.authDomain=dummy" >> ./shared/src/jvmMain/resources/firebase.properties
          echo "firebase.projectId=dummy" >> ./shared/src/jvmMain/resources/firebase.properties
          echo "firebase.storageBucket=dummy" >> ./shared/src/jvmMain/resources/firebase.properties
          echo "firebase.messagingSenderId=dummy" >> ./shared/src/jvmMain/resources/firebase.properties
          echo "firebase.appId=dummy" >> ./shared/src/jvmMain/resources/firebase.properties

      - name: Assemble Desktop App
        run: ./gradlew :composeApp:assemble

      - name: Run Desktop Tests
        run: ./gradlew :composeApp:desktopTest

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: desktop-test-results
          path: composeApp/build/reports/tests/desktopTest/
          retention-days: 7
